server:
  port: 8888

spring:
  application:
    name: gateway-eureka
  profiles:
    active: filters
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 是否开启通过注册中心进行路由转发的功能，通过 serviceId 转发到服务，默认为 false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

# 调整 gateway 包的 log 级别，以便排查问题。
logging:
  level:
    org.springframework.cloud.gateway: debug


# 将 Gateway 注册到服务中心之后，网关会自动代理所有的在注册中心的服务，访问这些服务的语法为：
# http://网关地址：端口/服务中心注册 serviceId/具体的 url